---
- name: Gather information about EC2 instances
  hosts: aws_ec2
    # Replace with a dynamic group name from the inventory output
  become: true
  gather_facts: yes
  vars:
    - ansible_ssh_private_key_file: "~/.ssh/tomer_keys2.pem"
  
  pre_tasks:
    - name: Print variable
      debug:
        msg: "{{ service }}<={{ version }}"
    - name: add hhost in a new format
      add_host:
        name: "new host group"
        groups: "{{ service }}"
    
  roles:
    - install 
  