# package_version: "{{ version }}"
# version_repo: mysql{{ package_version|string |replace(".", "") }}-community
packages:
  - mariadb
  - mysql-server
  - mysql-client 
  - python3-mysqldb
  - libmysqlclient-dev