---

# - name: Copy rpm file to server
#   get_url:
#      url: 
#      dest: ./files/package.rpm
#      mode: '0440'

- name: install rpm
  yum:
    name: https://dev.mysql.com/get/mysql84-community-release-el8-1.noarch.rpm
    state: present

# - name: Install {{ service }} of version {{ version }}
#   package:
#      name: "{{ item }}"
#      state: present
#   loop: "{{ packages }}"
#   become: yes

# - name: start service
#   ansible.builtin.service:
#     name: "{{ service }}"
#     enabled: yes
#     state: started

