---

- name: Copy rpm file to server
  copy:
     src: /home/ec2-user/Final_workshop_ansible/{{ item }}
     dest: /home/ec2-user/package.rpm
  loop: "{{ packages }}"
- name: install rpm
  yum:
    name: package.rpm
    state: present
    disable_gpg_check: true

- name: start service
  ansible.builtin.service:
    name: "{{ service }}"
    enabled: yes
    state: started

