---

- name: Install {{ service }} of version {{ version }}
  yum:
     name: "{{ item }}"
     state: present
     enablerepo: "base,{{service}}.{{ version }}-community"
     disablerepo: "*"
  loop: "{{ packages }}"
  become: yes

# - name: start service
#   ansible.builtin.service:
#     name: "{{ service }}"
#     enabled: yes
#     state: started

