---
- name: Copy rpm file to server
  copy:
     src: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
     dest: ./files/package.rpm
# - name: install rpm
#   yum:
#     name: ./files/package.rpm
#     state: present

# - name: Install {{ service }} of version {{ version }}
#   package:
#      name: "{{ item }}"
#      state: present
#   loop: "{{ packages }}"
#   become: yes

# - name: start service
#   ansible.builtin.service:
#     name: "{{ service }}"
#     enabled: yes
#     state: started

