---
- name: check 
  debug:
    msg:
     path: "{{ item }}"
  loop: "{{ mysql }}"

# - name: Install {{ service }} of version {{ version }}
#   ansible.builtin.dnf:
#     name: "{{ service }}"
#     state: present
#     allow_downgrade: yes

# - name: start service
#   ansible.builtin.service:
#     name: "{{ service }}"
#     enabled: yes
#     state: started

