---
- name: Install {{ service }} of version {{ version }}
  ansible.builtin.dnf:
    name: "{{ service }}=={{ version }}"
    state: present

- name: start service
  ansible.builtin.service:
    name: "{{ service }}"
    enabled: yes
    state: started

