---
- name: Install {{ service }} of version {{ version }}
  ansible.builtin.apt:
    name: "{{ service }}={{ version }}"
    state: present
    allow_downgrade: yes

- name: start service
  ansible.builtin.service:
    name: "{{ service }}"
    enabled: yes
    state: started

