---

- name: Copy rpm file to server
  copy:
     src: ./"{{ package.rpm }}.value"
     dest: ~/package.rpm

- name: install rpm
  yum:
    name: package.rpm
    state: present

# - name: Install {{ service }} of version {{ version }}
#   package:
#      name: "{{ item }}"
#      state: present
#   loop: "{{ packages }}"
#   become: yes

# - name: start service
#   ansible.builtin.service:
#     name: "{{ service }}"
#     enabled: yes
#     state: started

