---
- name: check 

  debug:
    msg:
     path: "{{ item }}"
  loop: "{{ packages }}"

- name: Install {{ service }} of version {{ version }}
  ansible.builtin.dnf:
     Print: "{{ item }}"
     name: "{{ item }}"
     state: present
     allow_downgrade: yes
  loop: "{{ packages }}"

# - name: start service
#   ansible.builtin.service:
#     name: "{{ service }}"
#     enabled: yes
#     state: started

