---

- name: Copy rpm file to server
  copy:
     src: /home/ec2-user/Final_workshop_ansible/"{{ item }}"
     dest: /home/ec2-user/Final_workshop_ansible/package.rpm
  loop: "{{ packages }}"
- name: install rpm
  yum:
    name: package.rpm
    state: present

# - name: Install {{ service }} of version {{ version }}
#   package:
#      name: "{{ item }}"
#      state: present
#   loop: "{{ packages }}"
#   become: yes

# - name: start service
#   ansible.builtin.service:
#     name: "{{ service }}"
#     enabled: yes
#     state: started

