---

- name: Copy rpm file to server
  get_url:
     url: https://dev.mysql.com/downloads/file/?id=528546
     dest: ./files/package.rpm
     mode: '0440'
     
- name: install rpm
  yum:
    name: ./files/package.rpm
    state: present

# - name: Install {{ service }} of version {{ version }}
#   package:
#      name: "{{ item }}"
#      state: present
#   loop: "{{ packages }}"
#   become: yes

# - name: start service
#   ansible.builtin.service:
#     name: "{{ service }}"
#     enabled: yes
#     state: started

