---
- name: check 

  debug:
    msg:
     path: "{{ item.value }}"
  loop: "{{ lookup('ansible.builtin.vars', 'variabl' +packages) }}"

# - name: Install {{ service }} of version {{ version }}
#   ansible.builtin.dnf:
#     name: "{{ service }}"
#     state: present
#     allow_downgrade: yes

# - name: start service
#   ansible.builtin.service:
#     name: "{{ service }}"
#     enabled: yes
#     state: started

